# GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  Punkyoi_config = debug
endif
ifeq ($(config),release)
  Punkyoi_config = release
endif

PROJECTS := Punkyoi

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

Punkyoi:
ifneq (,$(Punkyoi_config))
	@echo "==== Building Punkyoi ($(Punkyoi_config)) ===="
	@${MAKE} --no-print-directory -C . -f Punkyoi.make config=$(Punkyoi_config)
endif

clean:
	@${MAKE} --no-print-directory -C . -f Punkyoi.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   Punkyoi"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"